// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qaydecznhgguybmjwalq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFheWRlY3puaGdndXlibWp3YWxxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwMzgwMjcsImV4cCI6MjA3MzYxNDAyN30.aIQLJfuBTkPjhfJ_Q6mA7zZEJjznfJA1sl2U0w1ju98";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});